package store

import "time"

// Session tracks a single M-Pesa STK Push payment attempt from initiation
// through to its terminal state. It is the central record that bridges
// the async gap between the x402 HTTP request cycle and Safaricom's
// callback-based payment confirmation.
//
// A session moves through a defined set of states (see state.go). Fields
// are populated progressively as the payment progresses:
//
//   - At CREATED: ID, State, Phone, Amount, Currency, Shortcode, CreatedAt, ExpiresAt
//   - At STK_PUSHED: CheckoutRequestID, MerchantRequestID (from Daraja)
//   - At CONFIRMED: MpesaReceiptNumber, ConfirmedAmount, ConfirmedPhone (from callback)
//   - At CONSUMED: ConsumedAt
type Session struct {
	// ID is a ULID — lexicographically sortable, URL-safe, and time-ordered.
	// Generated by the session manager at initiation time.
	ID string

	// State is the current lifecycle stage of this payment session.
	// See state.go for the full set of states and their meanings.
	State State

	// Phone is the payer's M-Pesa phone number in E.164 format.
	// Normalised from the caller-supplied value by session.normalizePhone
	// before the session is created.
	Phone string

	// Amount is the requested payment amount in whole KES units.
	// Set at session creation from the PaymentRequest.
	Amount int64

	// Currency is the ISO 4217 currency code. Always "KES" for M-Pesa Kenya.
	Currency string

	// Shortcode is the M-Pesa business paybill or till number that receives
	// the payment. Copied from the session manager's Config at creation time.
	Shortcode string

	// CheckoutRequestID is Daraja's UUID for this STK Push request.
	// Populated during the CREATED→STK_PUSHED transition.
	// Used as the primary key for the secondary index that maps Safaricom
	// callbacks back to sessions — Safaricom sends this ID in every callback.
	CheckoutRequestID string

	// MerchantRequestID is Daraja's secondary ID for this STK Push request.
	// Populated alongside CheckoutRequestID during CREATED→STK_PUSHED.
	// Retained for audit purposes; not used in payment flow logic.
	MerchantRequestID string

	// MpesaReceiptNumber is Safaricom's transaction receipt number.
	// Populated from the callback metadata during STK_PUSHED→CONFIRMED.
	// This is the identifier customers receive in their M-Pesa SMS receipt.
	MpesaReceiptNumber string

	// ConfirmedAmount is the amount Safaricom confirmed was actually charged.
	// Pointer — nil until the session reaches CONFIRMED state.
	// In normal operation this matches Amount, but storing the confirmed value
	// separately provides an audit trail.
	ConfirmedAmount *int64

	// ConfirmedPhone is the phone number Safaricom confirmed the charge was
	// applied to, in E.164 format. Pointer — nil until CONFIRMED.
	// Safaricom sends this as a numeric value in the callback payload;
	// the callback handler formats it as "+<digits>".
	ConfirmedPhone *string

	// CreatedAt is the time the session was created. Set at initiation.
	CreatedAt time.Time

	// ExpiresAt is the time after which the session will be transitioned to
	// TIMEOUT if no callback has been received. Set to CreatedAt + TTL
	// (default 90 seconds) at initiation.
	ExpiresAt time.Time

	// ConsumedAt is the time the session was atomically consumed by the x402
	// Gate middleware. Pointer — nil until the session reaches CONSUMED state.
	ConsumedAt *time.Time
}

// Update carries the subset of Session fields that may be written after a
// session is created. It is used by Transition and ConsumeIfConfirmed to
// apply partial updates atomically alongside the state change.
//
// All fields are pointers — nil means "do not update this field". This allows
// each transition to write only the fields that become known at that stage
// without clearing previously written values.
type Update struct {
	// CheckoutRequestID is set during CREATED→STK_PUSHED when Daraja returns
	// the correlation ID for the STK Push request.
	CheckoutRequestID *string

	// MerchantRequestID is set alongside CheckoutRequestID during CREATED→STK_PUSHED.
	MerchantRequestID *string

	// MpesaReceiptNumber is set during STK_PUSHED→CONFIRMED from the callback metadata.
	MpesaReceiptNumber *string

	// ConfirmedAmount is set during STK_PUSHED→CONFIRMED from the callback metadata.
	ConfirmedAmount *int64

	// ConfirmedPhone is set during STK_PUSHED→CONFIRMED from the callback metadata.
	ConfirmedPhone *string

	// ConsumedAt is set during CONFIRMED→CONSUMED by ConsumeIfConfirmed.
	ConsumedAt *time.Time
}

// STKPushRequest carries the parameters for a single Daraja STK Push HTTP call.
// It is defined in the store package to avoid a circular import between the
// session and auth packages — session constructs it, auth consumes it.
type STKPushRequest struct {
	// Token is the Daraja Bearer access token obtained from GetAccessToken.
	Token string

	// Password is the base64-encoded STK Push password generated from the
	// shortcode, passkey, and current EAT timestamp.
	Password string

	// Timestamp is the EAT-formatted timestamp (YYYYMMDDHHmmss) used to
	// generate the password. Must match the time of the token call.
	Timestamp string

	// Phone is the payer's M-Pesa phone number in E.164 format.
	Phone string

	// Amount is the payment amount in whole KES units.
	Amount int64

	// Shortcode is the M-Pesa business paybill or till number.
	Shortcode string

	// CallbackURL is the public HTTPS endpoint where Safaricom will POST
	// the STK Push result.
	CallbackURL string

	// Reference is the account reference shown on the M-Pesa prompt.
	Reference string

	// Desc is the transaction description shown on the M-Pesa prompt.
	Desc string
}